DevopsManager/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('', include('ManagerMaster.urls')),
]

ManagerMaster/urls.py
from django.urls import path, re_path

#from . import views
from .views import index, auth, database, apps, api, log, manage, msg, cmdb

app_name = 'ManagerMaster'
urlpatterns = [
    # 开放权限管理
    path('index/', index.server_index, name="index"),
    path('common/account/login/', auth.account_login, name='account_login'),
    path('common/account/logout/', auth.account_logout, name='account_logout'),
    path('common/account/change/', auth.account_change, name='account_change'),
    path('common/account/change/password/',auth.account_c_password, name='account_c_password'),
    path('common/account/register/', auth.account_register, name='account_register'),

    path('server/project/api/index/', api.api_index, name='api_index'),
    path('server/project/app/index/', apps.app_index, name='app_index'),
    path('server/project/log/index/', log.log_index, name='log_index'),

    # 用户管理
    path('admin/account/', auth.account_index,name='account_index'),
    path('admin/account/authority/<int:user_id>/', manage.account_authority,name='account_authority'),
    path('admin/account/edit/<int:user_id>/', auth.account_edit, name='account_edit'),
    path('admin/account/active/<int:user_id>/', auth.account_active, name='account_active'),
    path('admin/account/delete/<int:user_id>/', auth.account_delete, name='account_delete'),
    # 数据库实例管理
    path('admin/db/ds/', database.DataServicesIndex.as_view(), name="ds_index"),
    path('admin/db/ds/edit/', database.ds_edit, name="ds_edit"),
    path('admin/db/ds/edit/<int:ds_id>/', database.ds_edit, name="ds_edit"),
    path('admin/db/ds/delete/<int:ds_id>/', database.ds_delete, name="ds_delete"),
    # 数据库用户管理
    path('admin/db/user/', database.DbUserIndex.as_view(), name="dbuser_index"),
    path('admin/db/user/edit/', database.dbuser_edit, name="dbuser_edit"),
    path('admin/db/user/edit/<int:user_id>/', database.dbuser_edit, name="dbuser_edit"),
    path('admin/db/user/query/', database.dbuser_query, name="dbuser_query"),
    path('admin/db/user/delete/<int:user_id>/', database.dbuser_delete, name="dbuser_delete"),
    # 数据库管理
    path('admin/db/dn/', database.DbNodeIndex.as_view(), name="dn_index"),
    path('admin/db/dn/edit/', database.dn_edit, name="dn_edit"),
    path('admin/db/dn/edit/<int:dn_id>/', database.dn_edit, name="dn_edit"),
    path('admin/db/dn/delete/<int:dn_id>/', database.dn_delete, name="dn_delete"),

    # 项目管理
    path('admin/project/', manage.ServerProjectIndex.as_view(), name="project_index"),
    path('admin/project/edit/', manage.project_edit, name="project_edit"),
    path('admin/project/edit/<int:project_id>/', manage.project_edit, name="project_edit"),
    path('admin/project/<int:project_id>/delete/', manage.server_project_delete, name="project_delete"),

    # 服务管理
    path('server/project/<int:project_id>/app/add/', apps.app_add, name="app_add"),
    path('server/project/<int:project_id>/app/list/', apps.app_list, name="app_list"),
    path('server/project/<int:project_id>/app/log/', log.log_list, name="log_list"),
    # app管理
    path('server/project/<int:project_id>/app/<int:app_id>/detail/', apps.app_detail, name="app_detail"),
    path('server/project/<int:project_id>/app/<int:app_id>/edit/', apps.app_edit, name="app_edit"),
    path('server/project/<int:project_id>/app/<int:app_id>/delete/', apps.app_delete, name="app_delete"),
    path('server/project/<int:project_id>/app/<int:app_id>/log/', log.app_log, name='app_log'),
    # app执行
    path('server/project/<int:project_id>/app/<int:app_id>/task/log/', apps.task_log, name="task_log"),
    path('server/project/<int:project_id>/app/<int:app_id>/task/add/', apps.task_add, name="task_add"),
    path('server/project/<int:project_id>/app/<int:app_id>/task/rollback/', apps.task_rollback, name="task_rollback"),
    # api监控
    path('server/project/<int:project_id>/api/index/', api.api_detail, name="api_detail"),
    path('server/project/<int:project_id>/api/edit/', api.api_edit, name="api_edit"),
    path('server/project/<int:project_id>/api/delete/', api.api_delete, name="api_delete" ),

    path('server/db/<int:proj_id>/list/',database.db_list, name='db_list'),
    path('server/db/<int:proj_id>/<int:db_id>/add/', database.sql_edit, name='sql_edit'),
    path('server/db/<int:proj_id>/<int:db_id>/list/', database.sql_list, name='sql_list'),
    path('server/db/<int:proj_id>/<int:db_id>/examine/<int:sql_id>/', database.sql_examine, name='sql_examine'),
    path('server/db/<int:proj_id>/<int:db_id>/select/<int:sql_id>/', database.sql_examine, name='sql_select'),
    path('server/db/<int:proj_id>/<int:db_id>/detail/<int:sql_id>/', database.sql_detail, name='sql_detail'),

    # 留言
    path('message/index/', msg.message_list, name="message"),
    path('message/add/', msg.message_add, name="message_add"),
    path('message/detail/<int:pk>/', msg.message_detail, name="message_detail"),
    path('message/del/<int:pk>/', msg.message_del, name="message_del"),
    path('message/change/<int:pk><int:type>/', msg.message_change, name="message_change"),


    # CMDB
    path('admin/cmdb/', cmdb.CmdbIndex.as_view(), name="cmdb_manage_index"),
    path('server/cmdb/index/', cmdb.cmdb_index, name="cmdb_index"),
    path('server/cmdb/<int:cmdb_id>/', cmdb.cmdb_list, name="cmdb_list"),
    path('admin/cmdb/edit/', cmdb.cmdb_edit, name="cmdb_edit"),
    path('admin/cmdb/edit/<int:cmdb_id>/', cmdb.cmdb_edit, name="cmdb_edit"),


    # path('test/', msg.test, name="test"),

]

ManagerMaster/views/log.py
from django.shortcuts import render
from DevopsManager import settings
from django.urls import reverse
from django.http import FileResponse
import os
import re
import datetime
from ..models import *
from django.http import HttpResponseRedirect
RANDOM_NUMBER = 199999090122

def log_list(request,project_id):
    """显示指定项目组下APP日志
        /ManagerMaster/project/<int:project_id>/app/log/
        /ManagerMaster/project/<int:project_id>/app/<int:app_id>/log/
    """
    project_node = ProjectModel.objects.get(pk=project_id)
    user = request.user
    app_list =  []
    project_list = []
    comm_re = re.compile(reverse('ManagerMaster:log_list', args=(RANDOM_NUMBER,)
                                 ).replace(str(RANDOM_NUMBER), '([0-9]+)'))
    comm_re_one = re.compile(reverse('ManagerMaster:app_log',args=(RANDOM_NUMBER,RANDOM_NUMBER)
                                     ).replace(str(RANDOM_NUMBER), '([0-9]+)'))
    for url in request.session['authority']:
        gen_pid = comm_re.search(url)
        if gen_pid:
            pid = int(gen_pid.group(1))
            if project_id == pid:
                continue
            try:
                project_list.append(
                    ProjectModel.objects.get(pk=pid)
                )
            except:
                pass
            continue
        try:
            a = comm_re_one.search( url )
            pid, aid = a.group(1),a.group(2)
            if int(pid) == project_id:
                app_list.append(AppModel.objects.get(pk=int(aid)))
        except:
            pass
    return render(request,'log_list.html',{'project_node':project_node,
                                           'app_list':app_list,
                                           'project_list':project_list})

def app_log(request,project_id,app_id):
    '''查看指定项目下的日志文件'''
    app_node = AppModel.objects.get(pk=app_id)
    app_name = app_node.app_name
    app_log_path = os.path.join( settings.SERVER_LOG_PATH, app_name)
    if request.method == "GET" and 'download' in request.GET:
        download_file = request.GET['download'].strip()
        type = request.GET['type'].strip()
        if type:
            the_file_name = os.path.join( app_log_path,type,download_file)
        else:
            the_file_name = os.path.join( app_log_path,download_file)
        # return StreamingHttpResponse(file_iterator(the_file_name))
        f = open(the_file_name, 'rb')
        response = FileResponse(f, content_type='APPLICATION/OCTET-STREAM')  # 文件头设定可以让任意文件都能正确下载
        response['Content-Disposition'] = 'attachment;filename="{}"'.format(
            os.path.basename(download_file))
        response['Content-Length'] = os.path.getsize(the_file_name)
        return response

    file_list = []
    if os.path.isdir( app_log_path):
        for root,dirs,files in os.walk(app_log_path):
            ddir = root.split(app_log_path)[1].strip(os.sep)
            if files:
                for f in files:
                    real_f = os.path.join( root, f)
                    file_list.append(
                        {
                            'name' : f,
                            'dir' : ddir,
                            'mtime' : datetime.datetime.fromtimestamp(
                                os.path.getmtime(real_f)).strftime('%F %T'),
                            'size' : "{:.2f}".format(os.path.getsize(real_f)/1024), #单位为K
                        }
                    )
    return render(request,'app_log.html',{'file_list':file_list,'app_node':app_node,
                                          'project_id':project_id })


def log_index(request):
    """APP日志显示首页
    /ManagerMaster/project/<int:project_id>/app/log/
    /ManagerMaster/project/<int:project_id>/app/<int:app_id>/log/
    """
    comm_re = re.compile(reverse('ManagerMaster:log_list', args=(RANDOM_NUMBER,)
                                 ).replace(str(RANDOM_NUMBER), '([0-9]+)'))
    pro_list = []
    url_list = request.session['authority']
    for url in url_list:
        gen_pid = comm_re.search(url)
        if gen_pid:
            pid = int(gen_pid.group(1))
            if ProjectModel.objects.filter(pk=pid).exists():
                pro_list.append(pid)
    if pro_list:
        pro_list = list(set(pro_list))
        return HttpResponseRedirect(reverse('ManagerMaster:log_list',
                                            args=(pro_list[0],)))
    error = {
        'title': '无法找到相关项目',
        'code': 404,
        'msg': "无法找到相关的项目"
    }
    return render(request, 'error.html', {'error': error,
                                          'active': 'project_admin'})

# def db_index(request):
#     """db展示首页
#     根据不同项目组进行分类，根据权限确认项目及db展示
#     /ManagerMaster/data/<int:project_id>/<int:db_id>/detail/
#     """
#     proj_list = []
#     proj_list = ProjectModel.objects.values('id','project_name')

templates/db_list.html
{% extends 'base.html' %}
{% load mytemplate %}
{% block title %}
    {{ proj_node.project_name }} DB列表
{% endblock %}
{% block before_file %}
    <!-- DataTables -->
    <link rel="stylesheet" href="/static/plugins/bower_components/datatables/dataTables.bootstrap.min.css">
{% endblock %}
{% block js %}
{% endblock %}

{% block css %}


{% endblock %}
{% block topic %}{{ proj_node.project_name }} DB列表{% endblock %}
{% block topic_list %}
    <li><a href="{% url 'ManagerMaster:app_list' proj_node.id %}">{{ proj_node.project_name }}</a></li>
    <li><a href="{% url 'ManagerMaster:db_list' proj_node.id %}">DB列表</a></li>
    <li class="active">{{ proj_node.project_name }} DB列表</li>
{% endblock %}
{% block content %}
    <div class="col-lg-12 col-sm-12 col-xs-12">
        <div class="white-box">
            <div class="box-title m-b-30"><h3>{{ proj_node.project_name }}</h3>
                <p class="text-muted m-b-40">数据库列表</p></div>
            <div>
                <table class="table table-hover manage-u-table">
                    <thead>
                    <tr>
                        <th class="text-center">#</th>
                        <th>用途</th>
                        <th>库名</th>
                        <th>数据库实例</th>
                        <th>数据库用户</th>
                        <th>备注</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if db_list %}
                        {% for db in db_list %}
                            <tr>
                                <td class="text-center"><small class="label label-success">{{ forloop.counter }}</small></td>
                                <td>{{ db.name }}</td>
                                <td>{{ db.db_name }}</td>
                                <td>{{ db.d_s }},{{ request.user.id }}</td>
                                <td name="query_user">{{ db.user }}</td>
                                <td>
                                    <span data-toggle="tooltip" title="{{ db.mark }}." data-placement="right">{{ db.mark|slice:"10" }}...</span>
                                </td>
                                    <td>
                                        <div class="button-box">
                                        {% my_if 'ManagerMaster:sql_list' 'proj_node.id' 'db.id' in request.session.authority %}
                                            <a class="btn btn-default" href="{% url 'ManagerMaster:sql_list' proj_node.id db.id %}">SQL管理</a>
                                        {% endif %}
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block after_file %}
    <!-- DataTables -->
    <script src="/static/plugins/bower_components/datatables/jquery.dataTables.min.js"></script>
    <script src="/static/plugins/bower_components/datatables/dataTables.bootstrap.min.js"></script>
{% endblock %}
{% block endjs %}
    <script>
        $("td[name='query_user']").each(function (i,o) {
            $.ajax({
                type: "get",
                url: "{% url 'ManagerMaster:dbuser_query' %}?ids="+$(o).text(),
                success: function (data) {
                    var jsonObj = $.parseJSON(data);
                    $(o).text('');
                    $.each(jsonObj,function (n,value) {
                        if( i % 2 == 1 ){
                            $(o).append('<code>'+value['name']+'</code>  ');
                        }else{
                            $(o).append('<code>'+value['name']+'</code>  ');
                        }
                        console.log( value['name']);
                        console.log("#################" + i );
                    })
                    }
                });
        })
    </script>
{% endblock %}

templates/dn_index.html
{% extends 'base.html' %}
{% block title %}
    数据库实例
{% endblock %}
{% block before_file %}
    <!-- jQuery peity -->
    <script src="/static/plugins/bower_components/peity/jquery.peity.min.js"></script>
    <script src="/static/plugins/bower_components/peity/jquery.peity.init.js"></script>
    <!-- Sweet-Alert  -->
    <script src="/static/plugins/bower_components/sweetalert/sweetalert.min.js"></script>
    <script src="/static/plugins/bower_components/sweetalert/jquery.sweet-alert.custom.js"></script>
    <!--alerts CSS -->
    <link href="/static/plugins/bower_components/sweetalert/sweetalert.css" rel="stylesheet" type="text/css">
{% endblock %}
{% block js %}
    $(function () {
    $("[data-toggle='tooltip']").tooltip();
    });
{% endblock %}
{% block css %}
    {#    <style>#}
    {#        .btn.mytooltip {#}
    {#            white-space: normal;#}
    {#            z-index: 100;#}
    {#        }#}
    {#    </style>#}
{% endblock %}
{% block topic %}数据库实例{% endblock %}
{% block topic_list %}
    <li class="active">数据库</li>
{% endblock %}
{% block content %}

    <div class="col-sm-12">
        <div class="white-box ">

            <div class="row box-title">
                <div class="col-sm-11"><h3>数据库列表</h3></div>
                <div class="col-sm-1">
                    <button class="btn btn-info btn-outline" onclick="location='{% url 'ManagerMaster:dn_edit' %}'">新增数据库</button>
                </div>
            </div>


            <hr>

            <div class="table-responsive row">
                <table class="table table-hover manage-u-table">
                    <thead>
                    <tr>
                        <th class="text-center">#</th>
                        <th>名称</th>
                        <th>库名</th>
                        <th>数据库实例</th>
                        <th>数据库用户</th>
                        <th>所属项目</th>
                        <th>备注</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if dn_list %}
                        {% for dn in dn_list %}
                            <tr>
                                <td class="text-center"><small class="label label-success">{{ forloop.counter }}</small></td>
                                <td>{{ dn.name }}</td>
                                <td>{{ dn.db_name }}</td>
                                <td>{{ dn.d_s }}</td>
                                <td name="query_user">{{ dn.user }}</td>
                                <td>{{ dn.project }}</td>
                                <td>
                                    <span data-toggle="tooltip" title="{{ dn.mark }}." data-placement="right">{{ dn.mark|slice:"8" }}...</span>
                                </td>
                                <td>
                                    <a type="button" class="btn btn-info btn-outline btn-circle m-r-5"
                                       href="{% url 'ManagerMaster:dn_edit' dn.id %}" data-toggle="tooltip" title="修改 {{ dn.name }} 数据" data-placement="left">
                                        <i class="ti-pencil-alt"></i>
                                    </a>
                                    <button type="button" alt="alert" id="del_{{ dn.id }}" class="btn btn-danger btn-outline btn-circle  m-r-5 img-responsive model_img " data-url="{% url 'ManagerMaster:dn_delete' dn.id %}" data-name="{{ dn.name }}" data-toggle="tooltip" title="删除 {{ dn.name }}">
                                        <i class="ti-trash"></i>
                                    </button>
                                </td>
                            </tr>
                        {% endfor %}
                    {% endif %}
                    </tbody>
                </table>
            </div>

        </div>
    </div>


{% endblock %}
{% block after_file %}
{% endblock %}
{% block endjs %}
    <script>
        $("[id^='del_']").on("click", function(){
            var _this = $(this);
            swal({
                title: "请确定",
                text: "是否删除 " + _this.data('name') + " 项目",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "删除",
                cancelButtonText: "取消",
                closeOnConfirm: false
            }, function(isConfirm) {
                if (isConfirm)
                    $.ajax({
                        type: "get",
                        url: _this.data('url'),
                        success: function (data) {
                            var sec=3000;
                            var title='错误!!!';
                            isConfirm=false
                            if ( !data.match("^\{(.+:.+,*){1,}\}$")) {
                                msg="删除接口异常!"
                            }
                            var d = $.parseJSON(data);
                            var msg = d.msg.toString();
                            if (d.code == 0 ){
                                title='成功';
                                sec=2000;
                                isConfirm=true
                            }
                            swal({
                                title: title,
                                type: "warning",
                                text: msg,
                                timer: sec,
                                showConfirmButton: isConfirm
                            }, function(){
                                window.location.reload();
                            });
                        }
                    });
            });
        });

        $("td[name='query_user']").each(function (i,o) {
            $.ajax({
                type: "get",
                url: "{% url 'ManagerMaster:dbuser_query' %}?ids="+$(o).text(),
                success: function (data) {
                    var jsonObj = $.parseJSON(data);
                    $(o).text('');
                    $.each(jsonObj,function (n,value) {
                        if( i % 2 == 1 ){
                            $(o).append('<code>'+value['name']+'</code>  ');
                        }else{
                            $(o).append('<code>'+value['name']+'</code>  ');
                        }
                        console.log( value['name']);
                        console.log("#################" + i );
                    })
                    {#var jsonStr1 = JSON.stringify(jsonObj)#}
                    {#console.log(jsonStr1+"jsonStr1")#}
                    {#var jsonArr = [];#}
                    {#for(var i =0 ;i < jsonObj.length;i++){#}
                    {#    jsonArr[i] = jsonObj[i];#}
                    {#}#}
                        {#console.log(typeof(jsonArr))#}
                    }
                });
        })
    </script>
{% endblock %}

templates/error.html
{% extends 'base.html' %}

{% block title %}{% endblock %}
{% block head %}{% endblock %}
{% block before_file %}{% endblock %}
{% block js %}
    <script>
        {% if active  %}
        $(function () {
            $("#{{ active }}").addClass("active");
        })
        {% endif %}
    </script>
{% endblock %}
{% block css %}{% endblock %}


{% block topic %}{{ error.title }}{% endblock %}
{% block remark %}{% endblock %}
{%  block topic_list %}
        <li><a href="#">error</a></li>
{% endblock %}

{% block content %}

    <!-- Main content -->
    <section class="content">

      <div class="error-page">
        <h2 class="headline text-red">{{ error.code }}</h2>

        <div class="error-content">
          <h3><i class="fa fa-warning text-red"></i> {{ error.title }}.</h3>

          <p>
            {{ error.msg }}.
          </p>

          <form class="search-form">
            <div class="input-group">
              <input type="text" name="search" class="form-control" placeholder="Search">

              <div class="input-group-btn">
                <button type="submit" name="submit" class="btn btn-danger btn-flat"><i class="fa fa-search"></i>
                </button>
              </div>
            </div>
            <!-- /.input-group -->
          </form>
        </div>
      </div>
      <!-- /.error-page -->

    </section>
    <!-- /.content -->

{% endblock %}
{% block after_file %}
{% endblock %}

templates/monitor_denied.html
{% extends 'base.html' %}
{% load mytemplate %}
{% block title %}应用管理{% endblock %}
{% block head %}{% endblock %}
{% block before_file %}
    <!-- DataTables -->
    <link rel="stylesheet" href="/static/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">

{% endblock %}
{% block js %}
    <script>
        $(function () {
            var arr = new Array("monitorapi_admin");
            add_active(arr);
        })


    </script>
{% endblock %}

{% block topic %} API监控 {% endblock %}
{% block remark %}{% endblock %}
{% block topic_list %}
    <li><a href="#">监控列表</a></li>
{% endblock %}

{% block content %}


<!-- Main content -->

<section class="content">


    <div class="nav-tabs-custom">

        <div class="tab-content">
            <div class="tab-pane active" id="tab_1">

                    <div class="callout callout-danger">
                        <h4>禁止!</h4>
                        没有访问权限
                    </div>


            </div>
        </div>
    </div>
</section>


{% endblock %}
{% block after_file %}
    <!-- DataTables -->
    <script src="/static/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/static/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>


{% endblock %}
{% block endjs %}
    <script>

        $(function () {

            get_data();
            /*3轮询读取函数*/
            setInterval(function () {
                get_data();
            }, 5000);
        })
    </script>

{% endblock %}

templates/msg_index.html
{% extends 'base.html' %}
{% block title %}用户管理{% endblock %}

{% block before_file %}
{% endblock %}
{% block js %}
    <script>
        $(function () {
            var arr = new Array("admin","account");
            add_active(arr);
        })
    </script>
{% endblock %}

{% block css %}
    <style>
        .example-modal .modal {
            position: relative;
            top: auto;
            bottom: auto;
            right: auto;
            left: auto;
            display: block;
            z-index: 1;
        }

        .example-modal .modal {
            background: transparent !important;
        }
    </style>
{% endblock %}

{% block topic %}用户管理{% endblock %}
{% block remark %}{% endblock %}
{% block topic_list %}
    <li><a href="{% url 'ManagerMaster:account_index' %}">用户管理</a></li>
{% endblock %}

{% block content %}
    <!-- Main content -->
    <section class="content">
        {% if type == "error" %}
            <div class="callout callout-danger">
                <h4>失败!</h4>
                {{ msg }}
            </div>
        {% elif type == "success" %}
            <div class="callout callout-success">
                <h4>成功!</h4>
                {{ msg }}
            </div>

        {% endif %}
        <div class="row">
            <div class="col-md-12">
                <div class="box">

                    <div class="box-header">
                        <h3 class="box-title"><a href="{% url 'ManagerMaster:account_register' %}" type="button" class="btn btn-info">用户新增</a></h3>

                        <div class="box-tools">
                            <div class="input-group input-group-sm" style="width: 150px;">
                                <input type="text" name="table_search" class="form-control pull-right"
                                       placeholder="Search">

                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i>
                                    </button>

                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- /.box-header -->
                    <div class="box-body">
                        <table class="table table-bordered" style="word-break:break-all; word-wrap:break-all;">

                            <tr>
                                <th>Id</th>
                                <th style="width:20%">用户名</th>
                                <th >邮箱</th>
                                <th>最新登录时间</th>
                                <th >Action</th>
                            </tr>


                            {% if user_list %}
                                {% for user in user_list %}
                                    <tr>
                                        <td><small class="label bg-green">{{ user.id }}</small></td>
                                        <td>{{ user.username }}</td>
                                        <td>{{ user.email }}</td>
                                        <td>{% if user.last_login %}
                                            {{ user.last_login |date:"Y-m-d H:m" }}
                                        {% else %}
                                            无记录
                                        {% endif %}
                                        </td>

                                        <td>
                                            <div class="input-group-btn">
                                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Action
                                                    <span class="fa fa-caret-down"></span></button>
                                                <ul class="dropdown-menu">
                                                    <li><a href="{% url 'ManagerMaster:account_edit' user.id %}">修改</a></li>
                                                    <li><a href="{% url 'ManagerMaster:account_authority' user.id %}">权限配置</a></li>

                                                    <li class="divider"></li>
                                                    <li><a type="button"  data-toggle="modal"
                                                           data-target="#modal-warning{{ user.id }}">删除</a></li>
                                                </ul>
                                            </div>

                                            <div class="modal modal-warning fade" id="modal-warning{{ user.id }}">
                                                <div class="modal-dialog">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <button type="button" class="close" data-dismiss="modal"
                                                                    aria-label="Close">
                                                                <span aria-hidden="true">&times;</span></button>
                                                            <h4 class="modal-title">警告</h4>
                                                        </div>
                                                        <div class="modal-body">
                                                            <p>确认是否执行删除操作</p>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-outline pull-left"
                                                                    data-dismiss="modal">Close
                                                            </button>

                                                            <a href="{% url 'ManagerMaster:account_delete' user.id %}"
                                                               class="btn btn-outline">确认</a>
                                                        </div>
                                                    </div>
                                                    <!-- /.modal-content -->
                                                </div>
                                                <!-- /.modal-dialog -->
                                            </div>
                                            <!-- /.modal -->

                                        </td>
                                    </tr>
                                {% endfor %}
                            {% endif %}


                        </table>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer clearfix">
                        <ul class="pagination pagination-sm no-margin pull-right">
                            <li><a href="#">&laquo;</a></li>

                            <li><a href="#">&raquo;</a></li>
                        </ul>
                    </div>
                </div>
                <!-- /.box -->
            </div>

        </div>
    </section>

{% endblock %}
{% block after_file %}

{% endblock %}